## Site settings
title: GDG Porto
title_min: GDGPORTO
email:  mail@gdgporto.xyz
description: > # this means to ignore newlines until "baseurl:"
 Google Developer Group Porto.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gdgporto.github.io" # the base hostname & protocol for your site
url_dev: "http://localhost:4000"
twitter_username: gdgporto
github_username:  GDGPorto

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

pages:
  - title: Home
    url: /
  - title: Eventos
    url: /eventos
  - title: Sobre GDG
    url: /sobre


exclude: ['package.json', '_src', 'node_modules', 'vendor/bundle/ruby']
